export const injectKeyPointTypes= Symbol()
export const injectKeyPointMoveModes= Symbol()
export const injectKeyPointActions= Symbol()
export const injectKeyCNTextMap = Symbol()
export const injectKeyIconMap= Symbol()
export const injectKeyRegions = Symbol()
